steps:
  # Copy all static files to the GCS bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '.'
      - 'gs://${_BUCKET_NAME}/'
    dir: 'src'

  # Set the bucket to serve static websites
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - 'web'
      - 'set'
      - '-m'
      - 'index.html'
      - 'gs://${_BUCKET_NAME}'

  # Make all files publicly readable
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'acl'
      - 'ch'
      - '-u'
      - 'AllUsers:R'
      - 'gs://${_BUCKET_NAME}/**'

# Substitution variables - set these when triggering the build
substitutions:
  _BUCKET_NAME: 'hjerteoghjem'  # Replace with your actual bucket name
